name: Pull request to unstable

on:
  pull_request:
    types: [opened]
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "REPOSITORY_OWNER=$(jq -r .repository.owner.login $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=$(jq -r .repository.name $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "SOURCE_COMMIT=$(jq -r .pull_request.head.sha $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
      - run: |
          git init
          git remote add origin "https://${{secrets.VCS_PAT}}@github.com/${REPOSITORY_OWNER}/${REPOSITORY_NAME}.git"
          git fetch --depth=1 origin "${SOURCE_COMMIT}"
          git checkout FETCH_HEAD
