name: Pull request to unstable

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - unstable

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "REPOSITORY_OWNER=${{github.event.repository.owner.login}}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${{github.event.repository.name}}" >> $GITHUB_ENV
          echo "SOURCE_COMMIT=${{github.event.pull_request.head.sha}}" >> $GITHUB_ENV
      - env:
          VCS_PAT: ${{secrets.VCS_PAT}}
        run: |
          docker run -id --name container kepocnhh/ci-java-lib-amd64/0.1b
          docker exec container /usr/local/bin/bash -c unstable/vcs/pr.sh
